### ISSUE TITLE
能不能提供一下$_FILES上传的具体用法

### ISSUE THREAD

**Issue by Liangkk** [gaoming13/HttpCurl#2]
\HttpCurl::post('http://api.example.com/', array(
    'file1'=>'@/data/sky.jpg',
    'file2'=>'@/data/bird.jpg',
 ));
此用法中, 'file1'=>'@/data/sky.jpg',参数是什么意思?如果'@/data/sky.jpg'是相对路径的话,$_FILES是获取不了文件的相对路径的吧~只有一个tmp的临时路径

**Comment by gaoming13** [comment]
这个类库处理时：参数前面没有@的被认为是正常的字符串参数，有@的被认为是要上传的文件，@后面是文件的绝对路径

另外类库更新了，新的使用方法：

```
HttpCurl::request('http://example.com/', 'post', array(
    'file1' => '@/data/sky.jpg',
    'file2' => '@/data/bird.jpg'
));
```

**Comment by Liangkk** [comment]
那意思是说,先要在本地上传一次,然后获取到图片的绝对路径,再远程上传一次~?$_FILES或者<input type='file'>不可以获取图片的绝对路径吧~

**Comment by gaoming13** [comment]
是的，要上传图片到远程服务器，本地一定要有这个图片的，curl才能把这个图片传到远程。

服务器那边接收图片后，会自动把它保存到临时目录，$_FILES会得到这个文件临时目录路径
